/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.dlp.controller;import cn.zhuatech.dlp.common.ApiResponse;import cn.zhuatech.dlp.service.DataPolicyExceptionService;import jakarta.validation.Valid;import org.springframework.web.bind.annotation.*;/**
                                                                                                                                                                                                                         * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                         */
@RestController @RequestMapping("/api/enterprise/dlp")public class DataPolicyExceptionController{private final DataPolicyExceptionService service;/**
                                                                                                                                                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                           */
public DataPolicyExceptionController(DataPolicyExceptionService service){this.service=service;}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          */
@PostMapping("/policy-exception")public ApiResponse<DataPolicyExceptionService.Assessment>assess(@Valid @RequestBody DataPolicyExceptionService.Request request){return ApiResponse.ok(service.assess(request));}}
