/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.dlp.service;import org.junit.jupiter.api.Test;import static org.assertj.core.api.Assertions.assertThat;/**
                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                            */
class DataPolicyExceptionServiceTest{private final DataPolicyExceptionService service=new DataPolicyExceptionService();/**
                                                                                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                   */
@Test void approvesControlledException(){var r=service.assess(new DataPolicyExceptionService.Request("X1",true,true,true,true,true,7,true,true,true));assertThat(r.decision()).isEqualTo(DataPolicyExceptionService.Decision.APPROVE);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          */
@Test void blocksUnapprovedException(){var r=service.assess(new DataPolicyExceptionService.Request("X2",true,false,false,false,false,60,true,true,true));assertThat(r.blockers()).hasSize(5);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        */
@Test void reviewsProtectionGaps(){var r=service.assess(new DataPolicyExceptionService.Request("X3",false,true,true,false,true,7,false,false,false));assertThat(r.actions()).hasSize(3);}}
